services:
  # Service 1: The Database
  # Replacing your local pgAdmin/Postgres installation with this container.
#  postgres:
#    image: postgres:15-alpine
#    container_name: ticketease-db
#    environment:
#      POSTGRES_USER: ticketease
#      POSTGRES_PASSWORD: password123
#      POSTGRES_DB: ticket_db
#    ports:
#      - "5432:5432"  # Maps container port 5432 to laptop port 5432
#    volumes:
#      - postgres_data:/var/lib/postgresql/data  # Persist data so it doesn't vanish when we restart

  # Service 2: Your Application
  app:
    # build: .   Build the Dockerfile in the current directory
    image: shafkat4/ticketease-app:latest
    container_name: ticketease-app
    environment:
      # CRITICAL: Override the application.properties settings here!
      # Instead of 'localhost', we use the service name 'postgres' defined above.
      # Docker will pull these values from the .env file we created in the GitHub Action
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "8080"
#    depends_on:
#      - postgres  # Wait for DB to start before starting App

  caddy:
    image: caddy:2-alpine
    container_name: ticketease-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile  # Mount config
      - caddy_data:/data                  # Persist SSL certificates
      - caddy_config:/config
    depends_on:
        - app

#volumes:
#  postgres_data:  # Define the storage volume

volumes:
  # ... other volumes ...
  caddy_data:
  caddy_config: